### ISSUE TITLE
Update to react 16.8.6

### ISSUE THREAD

**Issue by michaelzoidl** [birkir/react-children-addons#1]
Hey Birkir,

awesome package, this is exactly what i was looking for. :)
I would love to use your package, but i've seen the react version of this package is a bit out of date. 

Do you think we can update the version to the current version? (16.8.6)
Otherwise my project would need two different react versions which increases the build size and could lead to errors 😱 

Just adding the `^` caret to `react` and `react-is` would fix that :)
```
"react": "^16.6.0",
"react-is": "^16.6.0"
```

**Comment by birkir** [comment]
Whoops, my bad @michaelzoidl

**Comment by birkir** [comment]
Released with 1.0.9! 👍
